/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIlanjutanCheckidealtubuh;

import javax.swing.JOptionPane;

/**
 *
 * @author rendi
 */
public class IdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form IdealTubuh
     */
    public IdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        grubbutton = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try {
            Nama =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "GUIlanjutanCheckidealtubuh.IdealTubuh_Nama");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel3 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        Coba = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        grubbutton.add(jRadioButton1);
        jRadioButton1.setText("LAKI-LAKI");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(190, 160, 90, 23);

        grubbutton.add(jRadioButton2);
        jRadioButton2.setText("PEREMPUAN");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(300, 160, 120, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CECK IDEAL TUBUH ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 145, 17);

        jLabel2.setText("Nama         :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 40, 70, 14);
        getContentPane().add(Nama);
        Nama.setBounds(180, 40, 203, 30);

        jLabel3.setText("Tinggi         :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 90, 70, 14);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(180, 80, 72, 30);

        jLabel4.setText("Cm");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 90, 30, 14);

        jLabel5.setText("Berat          :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 130, 70, 14);
        getContentPane().add(Berat);
        Berat.setBounds(180, 120, 71, 30);

        jLabel6.setText("Kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 130, 20, 14);

        jLabel7.setText("Jenis kelamin :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 164, 69, 20);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(190, 190, 70, 30);

        Coba.setText("Coba Lagi");
        Coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobaActionPerformed(evt);
            }
        });
        getContentPane().add(Coba);
        Coba.setBounds(270, 190, 90, 30);

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 190, 70, 30);

        jLabel8.setText("Berat badan ideal anda adalah   :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 240, 159, 30);
        getContentPane().add(ideal);
        ideal.setBounds(280, 240, 96, 30);

        jLabel9.setText("Kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 240, 30, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Hasil diagnosa Kesehatan badan anda");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 310, 231, 15);
        getContentPane().add(hasil);
        hasil.setBounds(110, 340, 410, 30);
        getContentPane().add(saran);
        saran.setBounds(110, 380, 410, 30);

        jPanel3.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(70, 0, 490, 470);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 80, 470);

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(560, 0, 80, 470);

        setSize(new java.awt.Dimension(655, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        try    {
        int ti= Integer.valueOf(Tinggi.getText());
       int bt= Integer.valueOf(Berat.getText());
       String nama = String.valueOf(Nama.getText());
       int h1=0;
       double temp;
       if (jRadioButton1.isSelected()){
           h1 = (ti-104);}
        else if (jRadioButton2.isSelected()){
           h1 = (ti-100);
       }
        String Ideal=Integer.toString( h1);
       
       if(h1<bt){
           ideal.setText(Ideal);
           hasil.setText("Maaf "+nama+" sepertinya anda terlalu gendut :(");
           saran.setText("Banyaklah mengkonsumsi syuran dan puasa agar anda tidak di bully");
           }else if(h1>bt){
           ideal.setText(Ideal);
           hasil.setText("Maaf "+nama+" sepertinya anda terlalu kuus :(");
           saran.setText("Banyaklah mengkonsumsi makanan berkarbohidrat dan berlemak anda bahagia");
           }else if (bt==h1) {
           ideal.setText(Ideal);
           hasil.setText("WAWW "+nama+" sepertinya anda cool & tajir :)");
           saran.setText("pertahankan dan jaga pola makan anda seperti anda menjaga kekasih hatimu :)");
           }
     
       
        
     }catch (Exception e){
         JOptionPane.showMessageDialog(null,"Error!! kotak isi semua dong");
     }
    }//GEN-LAST:event_HitungActionPerformed

    private void CobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobaActionPerformed
Tinggi.setText("");
Berat.setText("");
Nama.setText("");
grubbutton.clearSelection();
saran.setText("");
hasil.setText("");
ideal.setText("");

                

    }//GEN-LAST:event_CobaActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JButton Coba;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup grubbutton;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField saran;
    // End of variables declaration//GEN-END:variables

    private String getText(double h1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
